### ISSUE TITLE
Markdown transformation to Normalized DITA output generates wrong dtd in xml header

### ISSUE THREAD

**Issue by ritti** [jelovirt/org.lwdita#10]
## Intention
I want to make use of the tip on tip of the DITA-OT release notes:

## Input
I have a Test.ditamap that references one markdown file that has two headers.
```xml
<map>
  <topicref href="test.md" format="markdown"/>
</map>
```
test.md file:
```
# Header 1 Level 1
# Header 2 Level 1
```
## DITA command
Transform to Normalized DITA output
```
"C:\Program Files\DITA-OT\dita-ot-3.0.3\bin\dita" -input=Test.ditamap --format=dita
```
## Result
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dita
  PUBLIC "-//OASIS//DTD DITA Composite//EN" "dita.dtd">
<dita>
	<topic id="header-1-level-1">
		<title>Header 1 Level 1</title>
		<body/>
	</topic>
	<topic id="header-2-level-1">
		<title>Header 2 Level 1</title>
		<body/>
	</topic>
</dita>
```
## Expected Result
The referenced dtd should be **"ditabase.dtd"** instead of **"dita.dtd"**.
```
<!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "ditabase.dtd">```

## Additional Issues
I get 2 additional errors where I'm not sure if this should be errors
### Change the format of Test.ditamap to mdita
```xml
<map>
  <topicref href="test.md" format="mdita"/>
</map>
```

**Comment by jelovirt** [comment]
The system identifier in the doctype doesn't make any difference, so this is not really something that needs to be fixed.

The output is generated by https://github.com/dita-ot/org.dita.normalize and this should be reported there.
