### ISSUE TITLE
HTML <var> element not supported as input

### ISSUE THREAD

**Issue by robander** [jelovirt/org.lwdita#107]
I have MD files that are processed through DITA-OT 3.7. They include the `<var>` element, which I don't think is technically part of HDITA.

When DITA-OT processes that, it converts to
`<var class="- topic/var ">`

Later steps report the error, and treat it as an undefined phrase-like element (generating HTML with `<span class="undefined_element">`). Error is
`[xslt] file:/Users/...path.../file.md:181:15 [DOTX074W][WARN]: No formatting defined for unknown class attribute value "- topic/var ".` 

Probably want to either convert this to `<varname class="- topic/keyword sw-d/varname ">` or just to a phrase `<ph class="- topic/ph ">`

**Comment by jelovirt** [comment]
Yes, the current LwDITA draft doesn't have `<var>` HDITA element. I think the parser needs to at least throw an error, maybe recover by converting it to `<ph>`.
