### ISSUE TITLE
Various simple cases when DITA to markdown breaks table structure

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#136]
Tested with the 3.4.0 plugin.
There is also this issue #76 which covers other complex cases.
But here are some simple one:

1) DITA simple topic:
```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "topic.dtd">
<topic id="t1">
  <title>T1</title>
  <body>
    <simpletable id="simpletable_shc_sz3_lwb">
      <sthead>
        <stentry>
          <p>1</p>
        </stentry>
        <stentry>
          <p>2</p>
        </stentry>
      </sthead>
      <strow>
        <stentry>
          <p>abc</p>
        </stentry>
        <stentry>
          <p>def</p>
        </stentry>
      </strow>
    </simpletable>
  </body>
</topic>
```

is convered to:
```markdown
# T1 {#t1}

|1

|2

|
|---|---|
|abc

|def

|
```
  
So because those paragraphs are in the cells, there are new lines after them. But in LW DITA it's impossible to add plain text to a cell, you need to wrap it in a paragraph.

2) Similar simple table case with no table heading:
```xml
<topic id="t1">
  <title>T1</title>
  <body>
    <simpletable id="simpletable_shc_sz3_lwb">
      <strow>
        <stentry>
          <p>abc</p>
        </stentry>
        <stentry>
          <p>def</p>
        </stentry>
      </strow>
    </simpletable>
  </body>
</topic>
```
which converts to Markdown like this:
```markdown
# T1 {#t1}

|abc

|def

|
```
but even if there were no new lines, the Markdown table still needs a heading to be identified as a table.

3) DITA cals table without a heading:
```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="t2">
  <title>T2</title>
  <body>
    <p>
      <table frame="all" id="table_zld_wz3_lwb">
        <title>abc</title>
        <tgroup cols="2">
          <colspec colname="c1" colnum="1" colwidth="75pt"/>
          <colspec colname="c2" colnum="2" colwidth="75pt"/>
          <tbody>
            <row>
              <entry>chip1</entry>
              <entry>chip2</entry>
            </row>
          </tbody>
        </tgroup>
      </table>
    </p>
  </body>
</topic>
```
converts to this Markdown structure which is not a valid table, it lacks a heading:
```markdown
# T2 {#t2}

|chip1|chip2|
```

**Comment by jelovirt** [comment]
Cases 1 and 2 are easy to fix.

Case 3 is more tricky one, see https://stackoverflow.com/a/17543474/2679. About half of the Markdown flavours that support tables like this do *not* support headerless tables. Thus, if the default Markdown output would just omit the header, there would be many Markdown processors that would not be able to read the output correctly.

**Comment by raducoravu** [comment]
@jelovirt how about if for (3) we generate an empty heading row?

**Comment by raducoravu** [comment]
Thanks for the work @jelovirt 👍
