### ISSUE TITLE
ditavals applied to MDITA must use "props" instead of "data-props" 

### ISSUE THREAD

**Issue by darrenn-jackson** [jelovirt/org.lwdita#149]
The latest proposed LwDITA spec says that only the "data-props" attribute is supported for conditional processing.  XDITA, on the other hand, requires the "props" attribute. However, you use the "data-props" attribute in both your MDITA content and in the ditaval file, you'll get the following error during processing:

`[filter] [DOTJ031I][INFO] No specified rule for 'props=unneeded' was found in the ditaval file. This value will use the default action, or a parent prop action if specified. To remove this message, you can specify a rule for 'props=unneeded' in the ditaval file.`

After I changed my ditaval file to use "props" instead of "data-props", my conditional process works (at least both filtering and flagging).

The plugin should match the proposed spec by mapping/converting the "data-props" attribute in ditaval files to "props" internally. It seems to do this already for the MDITA source itself.

I tested this on DITA-OT 4.0.2, with OpenJDK version 17.0.6 (2023-01-17)

**Comment by jelovirt** [comment]
Added test #151 and IMO the code is correct. I may have misunderstood your test case, but if you have MDITA document

```markdown
<p data-props="audience(novice)">Novice content.</p>
```

This will be converted to DITA

```xml
<p class="- topic/p " props="audience(novice)">Novice content.</p>
```

and rest of the DITA-OT processing will filter based on the `props` attribute.

**Comment by darrenn-jackson** [comment]
@jelovirt maybe this is more of a documentation bug, because it was not clear to me that I had to use `props` in my ditaval files instead of `data-props` until I enabled the `-v` flag and saw that error message. I think others who are testing/piloting LwDITA will run into the same issue.

DITA-OT's behavior makes sense because you avoid needing redundant `props` and `data-props` lines in the ditaval file for the same effect for different source formats. But, in my earlier testing I thought conditional processing wasn't even supported for MDITA because my `<prop>` elements used `data-props`, which did nothing.

**Comment by jelovirt** [comment]
This needs to be clarified in LwDITA spec draft, but we should also document this in our wiki. Ping @infotexture if you have ideas where to stick this gotcha, I can try to describe it. We don't have a place for common _attributes_ handling yet.

**Comment by darrenn-jackson** [comment]
I created [this pull request for the wiki](https://github.com/dita-ot/docs/pull/469) three days ago using the oXygen web editor. We'll see what comes of it.

**Comment by infotexture** [comment]
@darrenn-jackson Thanks, saw the docs PR. Looks good at first glance.

Been traveling these past few days, but will take a closer look soon.
