### ISSUE TITLE
Incorrect error: Header level raised from 1 to 3 without intermediate header level

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#15]
I have a Markdown file like this:

             # Header 1
            
            This is a quote:
            
            ## Header 2
            
            List sample:
            
            ### Header 3
            
            Table sample.

It's conversion to "mdita" yields the error:

               Header level raised from 1 to 3 without intermediate header level

but there is no such problem in the Markdown which properly increases the header level.

**Comment by jelovirt** [comment]
The validation order was incorrect in MDITA reader. Now the correct "LwDITA does not support level 3 header" error message is thrown.

**Comment by raducoravu** [comment]
👍 Right.
