### ISSUE TITLE
Gradle ArchiveName property was deprecated and is not supported in Gradle 8.x

### ISSUE THREAD

**Issue by kirkilj** [jelovirt/org.lwdita#158]
We tried to see if we could simply build lwdita to test our environment. It failed initially, because my developer had installed gradle 8.x instead of 7.x, and a deprecated property ArchiveName was removed. Once he installed Gradle 7, he was able to build lwdita in VS-Code.

Apparently the new property name is [archiveFileName](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html?_ga=2.33544701.2112057204.1682527791-531247317.1682527791#org.gradle.api.tasks.bundling.Zip:archiveFileName)

Should some requirement be mentioned in the README?

**Comment by jelovirt** [comment]
Fixed in 4e739eb074f56b7c9dc8ab581c302a076ea5f17d
