### ISSUE TITLE
inline markup in `<pre>` processed in XDITA but not MDITA

### ISSUE THREAD

**Issue by darrenn-jackson** [jelovirt/org.lwdita#160]
The LwDITA grammar files from OASIS (I think) explicitly support LwDITA elements nested inside `<pre>` elements. In fact the following XDITA topic:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">
<topic id="preformatted-content">
  <title>Preformatted Content</title>
  <shortdesc>A test of code-like content block and inline processing</shortdesc>
  <body>
    <p>How does the content below render in HTML5?</p>
    <p></p>
<pre>
host# <b>ls -a</b>
. ..
</pre>
  </body>
</topic>
```

Transforms into the following HTML5. Note the bolding of the `ls -a` command:

```html
<!DOCTYPE html
   SYSTEM "about:legacy-compat">
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="copyright" content="(C) Copyright 2023">
      <meta name="generator" content="DITA-OT">
      <meta name="description" content="A test of code-like content block and inline processing">
      <title>Preformatted Content</title>
      <link rel="stylesheet" type="text/css" href="../commonltr.css">
   </head>
   <body id="preformatted-content">
      <main role="main">
         <article role="article" aria-labelledby="ariaid-title1">
            <h1 class="title topictitle1" id="ariaid-title1">Preformatted Content</h1>
            <div class="body">
               <p class="shortdesc">A test of code-like content block and inline processing</p>
               <p class="p">How does the content below render in HTML5?</p>
               <p class="p"></p>
               <pre class="pre">
ncn-w001# <strong class="ph b">ls -a</strong>
. ..
</pre>
            </div>
            <nav role="navigation" class="related-links">
               <div class="familylinks">
                  <div class="parentlink"><strong>Parent topic:</strong> <a class="link" href="../mdita/About.html">About this Publication</a></div>
               </div>
            </nav>
         </article>
      </main>
   </body>
</html>
``` 
That bolding does render as expected given the default CSS the `html5` transtype produces. However, this does not currently work in MDITA. This MDITA topic:

```markdown
# Preformatted content in MDITA

This tests how code blocks are handled by DITA-OT.

This is another paragraph.

    ```
    ncn-w001# **ls -l**
    . ..
    ```
```

Transforms into:

```html
<!DOCTYPE html
   SYSTEM "about:legacy-compat">
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="copyright" content="(C) Copyright 2023">
      <meta name="generator" content="DITA-OT">
      <meta name="description" content="This tests how code blocks are handled by DITA-OT.">
      <title>Preformatted content in MDITA</title>
      <link rel="stylesheet" type="text/css" href="../commonltr.css">
   </head>
   <body id="preformatted-content-in-mdita">
      <main role="main">
         <article role="article" aria-labelledby="ariaid-title1">
            <h1 class="title topictitle1" id="ariaid-title1">Preformatted content in MDITA</h1>
            <div class="body">
               <p class="shortdesc">This tests how code blocks are handled by DITA-OT.</p>
               <p class="p">This is another paragraph.</p>
               <pre class="pre"><span class="ph">host# **ls -l**
. ..</span></pre>
               <p class="p">More text</p>
            </div>
            <nav role="navigation" class="related-links">
               <div class="familylinks">
                  <div class="parentlink"><strong>Parent topic:</strong> <a class="link" href="../mdita/About.html">About this Publication</a></div>
               </div>
            </nav>
         </article>
      </main>
   </body>
</html>
```

Note that asterisks pass through instead of converting into the `<strong>`. This behavior is expected for non-MDITA Markdown because Markdown codeblocks just pass all containing characters right through without processing. The plugin is correctly converting the Markdown codeblock to a LwDITA `<pre>`, but it's just not processing the markup within the `<pre>`.

**Comment by jelovirt** [comment]
See CommonMark [fenced code block](https://spec.commonmark.org/0.30/#fenced-code-blocks):

> The content of a code fence is treated as literal text, not parsed as inlines.

So in this case XDITA has a feature that MDITA doesn't.

**Comment by darrenn-jackson** [comment]
This is a conflict between the processing rules for CommonMark and the information model of LwDITA/MDITA. Table 7.1 of the [latest committee node](http://docs.oasis-open.org/dita/LwDITA/v1.0/LwDITA-v1.0.html) says that MDITA fenced/indented code blocks map to LwDITA `<pre>` elements, which allow for inline markup & processing.  

So I think that DITA-OT should parse MDITA according to the LwDITA info model expressed in that note or in the [work-in-progress grammar files](https://github.com/oasis-tcs/dita-lwdita/blob/spec/org.oasis.xdita/) that are bundled with the XDITA plugin. Either that or make it clearer in the docs that MDITA processing deviates from the proposed standard in this area. 

But I argue for the former, since that would significantly narrow the feature gap between:

- MDITA and XDITA/HDITA 
- MDITA and other plaintext markup languages like reStructuredText and AsciiDoc (which both support inline markup in equivalent contexts)

Specifically, fixing this would enable in MDITA not only inline bolding in a `<pre>` but possibly also the new LwDITA highlighting and/or emphasis domains, which would be very useful to organizations like mine whose Markdown content consists of lots of examples of specific lines in YAML, JSON, unstructured text config files, where specific lines (or parts of a line) in an example file must be added, deleted or modified. 

So I think this is actually a very valid issue.

**Comment by jelovirt** [comment]
@darrenn-jackson you reference a note from 2018. The LwDITA spec draft is still just a draft, but this DITA-OT plug-in follows the spec draft, not the note from 2018.

**Comment by darrenn-jackson** [comment]
The spec draft doesn't (yet) say what elements are allowed inside others. The draft grammar files, which are maintained and developed in the same repo as the draft spec, do. If I'm reading those files correctly (which I may not), according to them it's valid for a `<b>` or `<strong>` to be within a `<pre>`:

 In https://github.com/oasis-tcs/dita-lwdita/blob/spec/org.oasis.xdita/dtd/lw-topic.mod it says that the `<pre>` can contain the `ph` entity:

```
<!--                    LONG NAME: Preformatted content -->
<!ELEMENT pre            (#PCDATA|%ph;|xref|%data;)*        >
<!ATTLIST pre
             %localization;
             %filters;
             %reuse;
             xml:space  (preserve)               #FIXED 'preserve'
             outputclass  CDATA          #IMPLIED
             class CDATA "- topic/pre ">
```

The https://github.com/oasis-tcs/dita-lwdita/blob/spec/org.oasis.xdita/dtd/lw-topic.dtd file defines that entity (which includes both `b` and `strong`):

```
<!-- hi-d and emphasis-d -->
<!ENTITY % ph           "b | em | i | ph | strong | sub | sup | tt | u"       >
```
