### ISSUE TITLE
XDITA `@format` must be `dita` not `xdita`

### ISSUE THREAD

**Issue by darrenn-jackson** [jelovirt/org.lwdita#161]
If a map contains an XDITA topic and you follow the advice in the [docs](https://www.dita-ot.org/dev/topics/lwdita-input.html), you'll get the following error when transforming:

```
[DOTX021E][ERROR]: Missing navtitle attribute or element for non-DITA resource "mdita/preformatted-content.xml". References must provide a local navigation title when the target is not a local DITA resource.
```
`mdita//preformatted-content.xml` is the path of my test XDITA topic. The `@format` of the XDITA `<topicref>` must be `dita`, not `xdita`. I suspect that this is a bug in the plugin and not the docs, but I'll create a docs PR if the docs must be fixed instead.

**Comment by jelovirt** [comment]
XDITA is not bundled by this plug-in. XDITA schemas is distributed by https://github.com/oasis-tcs/dita-lwdita and configuration for `xdita` should be in that plug-in.

Unfortunately the LwDITA SC hasn't released new versions of the DTDs since 2018.

**Comment by darrenn-jackson** [comment]
I double-checked my list of installed plugins and I don't have that installed. 

I have some follow-up questions:

1. Since I don't have that xdita plugin installed, how is DITA-OT processing the two XDITA (.xml) topics I have in my test map that include the `<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">` line? Does DITA-OT just ignore that explicit reference to the XDITA schema and just process XML files as DITA 1.3? That makes sense since LwDITA is a subset of DITA 1.3, but I'd still expect an error from DITA-OT because it couldn't find the XDITA DTD.
2. Should I create a docs PR to explicitly tell users that they must install the `org.oasis.xdita` plugin in order to get full LwDITA support? That way others testing LwDITA won't run into this same issue.

**Comment by darrenn-jackson** [comment]
@infotexture pointed out to me that release v0_2_2 of the XDITA plugin is already included in recent DITA-OT versions. In any event, this is really a bug that should be filed against the dita-lwdita plugin, not this one.
