### ISSUE TITLE
Re-enable MDITA backtick support and convert to LwDITA `<tt>`

### ISSUE THREAD

**Issue by darrenn-jackson** [jelovirt/org.lwdita#164]
The `<tt>` element was added to the [draft LwDITA spec last December](https://dita-lang.org/lwdita/introduction/revision-history.html). It was also added to the [draft topic DTD](https://github.com/oasis-tcs/dita-lwdita/blob/spec/org.oasis.xdita/dtd/lw-topic.dtd) at the same time. The draft says that this is implemented [in MDITA by backticks](https://dita-lang.org/lwdita/components/lw-tt.html). This is LwDITA's equivalent to `<codeph>`, support for which was recently removed from the plugin.

The plugin should re-enable support for backticks in MDITA content and process them as `<tt>`.

**Comment by jelovirt** [comment]
I don't understand this feature request. The MDITA implementation supports backticks and processes them as `<tt>`, as implemented in #130. Or is this about something else?

**Comment by darrenn-jackson** [comment]
I created this issue because this doesn't seem to work when transforming MDITA content with DITA-OT version 4.0.2. When using the `dita` transtype, the backticks become `<ph>`. The content within backticks also doesn't render as expected when using the `html5` transtype.

I thought my problem was caused by the old `org.oasis-open.xdita.v0_2_2` plugin that comes pre-installed with DITA-OT, so I uninstalled that I tried to to unistall the plugin files from the oasis-tcs/dita-lwdita repo, but that broke the build process with the error: `Error: Failed to run pipeline: begin 1, end 0, length 0`. I went down that path because I don't know if this plugin converts MDITA to DITA 1.3 and processes accordingly, or converts MDITA to XDITA (and therefore relies on the XDITA plugin for the real LwDITA feature support).

Here are the two files that I used to test:

The map:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Map//EN" "lw-map.dtd">
<map id="singleton">
  <topicmeta>
    <navtitle>Map to convert one topic</navtitle>
  </topicmeta>
  <topicref href="mdita/tt-test.md" format="mdita"/>
</map>
```

The topic referenced by the map:

```
# MDITA backtick processing

A simple topic to test backtick processing.

`rm -rf /`
```

**Comment by jelovirt** [comment]
LwDITA plug-in 5.4 will generate

```xml
<topic id="mdita-backtick-processing">
  <title>MDITA backtick processing</title>
  <shortdesc>A simple topic to test backtick processing.</shortdesc>
  <body>
    <p>
      <tt>rm -rf /</tt>
    </p>
  </body>
</topic>
```

as expected, it generates `<tt>` for backticks.

I think you're confusing DITA-OT and the LwDITA plug-in. DITA-OT bundles LwDITA plug-in, but in practice, the bundled plug-in is always an old release. You mention DITA-OT 4.0.2, which bundles LwDITA plug-in 3.3.
