### ISSUE TITLE
Output code spans for programming & software domain elements

### ISSUE THREAD

**Issue by infotexture** [jelovirt/org.lwdita#169]
When generating Markdown output from DITA, tags like `<cmdname>`, `<filepath>`, `<option>`, `<parmname>`, `<varname>`, etc. should wrap the element content in backticks to produce inline code spans.

**Comment by jelovirt** [comment]
In HTML5 output of DITA-OT for programming domain, e.g. `<parname>` and `<option>` are output as normal text. Should Markdown output kinda match what HTML5 output would be. That is, if we convert DITA to Markdown, and DITA to HTML5, and feed both of those to Pandoc, should the output approximately match? So in this case, monospace font or normal font.

**Comment by infotexture** [comment]
> In HTML5 output of DITA-OT for programming domain, e.g. `<parname>` and `<option>` are output as normal text. Should Markdown output kinda match what HTML5 output would be.

That's a good point, and one could certainly argue for consistency there. The difference is that the HTML5 output wraps these constructs in spans with class attributes that allow them to be styled via custom CSS if desired.

Since we can't do the same in Markdown, I'd prefer the inline code spans, but others might not.
