### ISSUE TITLE
Definition List in HDITA format not supported in MDITA

### ISSUE THREAD

**Issue by xephon2** [jelovirt/org.lwdita#17]
The specification says in table [7.1 DITA 1.3 element types in LwDITA](http://docs.oasis-open.org/dita/LwDITA/v1.0/LwDITA-v1.0.html#ariaid-title38) that definition lists are supported in MDITA by using the HDITA syntax. The definition list in markdown syntax is rendered, the HDITA syntax is not processed. Nothing appears in the PDF output. I'd like to use the HDITA syntax to filter `<dlentry>` elements.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="urn:oasis:names:tc:dita:rng:map.rng"
    schematypens="http://relaxng.org/ns/structure/1.0"?>
<map>
    <title>Test</title>
    <topicref href="test.md" format="mdita"/>
</map>
```

```markdown
# Test

Shortdesc

Term
:   Definition.

<dl>
    <dlentry>
        <dt>Term</dt>
        <dd>Definition</dd>
    </dlentry>
</dl>
```

**Comment by jelovirt** [comment]
The HDITA structure for definition list is

```html
<dl>
  <dt>Term</dt>
  <dd>Definition</dd>
</dl>
```

**Comment by jelovirt** [comment]
Make sure https://github.com/vsch/flexmark-java/wiki/Extensions#html-to-markdown is being used.

**Comment by jelovirt** [comment]
If you use HTML5 `<dl>` element structure correctly, the expected output is generated.
