### ISSUE TITLE
Support note type content in MDITA

### ISSUE THREAD

**Issue by darrenn-jackson** [jelovirt/org.lwdita#174]
Convert the [HDITA note syntax](https://dita-lang.org/lwdita/components/lw-note.html) in MDITA content so that it converts to the proper LwDITA `note` type.

**Comment by jelovirt** [comment]
The current LwDITA draft says HDITA has a `@type` attribute. This is not valid HTML5, so I assume it's something the SC has added without checking HTML5 spec first. I'm not going to add something like this that will likely be removed or changed into `@data-type` attribute.

The `data-class="note"` shouldn't be problematic to implement.

**Comment by jelovirt** [comment]
Raised https://github.com/oasis-tcs/dita-lwdita/issues/113 because the spec draft is not constant and like has a bug/obsolete text.
