### ISSUE TITLE
`<audio>` does not work

### ISSUE THREAD

**Issue by darrenn-jackson** [jelovirt/org.lwdita#180]
The plugin doesn't seem to support the `<audio>` LwDITA element. I created an MDITA topic that contains the following HDITA snippet, based on the example for the draft spec:

```html
<audio title="Alarm audio" controls>
  <source src="../Alarm10.wav">
  <p data-class="fallback">This music is not available.</p>
</audio>
```

When I use the default `html5` transtype, that markup becomes:

```html5
<object><param name="source">
  
  <p class="p">This music is not available.</p>
</object>
```

Which doesn't match the [syntax example for this element on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio).

This is the normalized DITA output (`dita` transtype):

```xml
<audio title="Alarm audio" controls="">
  <source name="source" src="../Alarm10.wav"/>
  <p data-class="fallback">This music is not available.</p>
</audio>
```

The October 2018 Committee Note says that the LwDITA multimedia elements would be added to a new domain in DITA 1.3, but there haven't been any changes to DITA 1.3 since June of 2018. But I do see that the latest draft of DITA 2.0 includes the `<audio>` and `<video>` multimedia domain elements. The draft LwDITA spec doesn't currently say what version of full DITA it's supposed to be a subset of. I think this all means that the LwDITA subcommittee changed its mind and LwDITA is no longer meant to be a fully conforming subset of DITA 1.3, but of 2.0 instead. 

Does this mean that the lwdita plugin must process MDITA/HDITA as DITA 2.0 in order to support these multimedia elements?

**Comment by jelovirt** [comment]
LwDITA plug-in should support parsing `<audio>`, but DITA-OT HTML5 output doesn't support audio yet.
