### ISSUE TITLE
Generated step elems do not have cmd inside them

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#189]
From this MD task:
```markdown
# Sample DITA Task {.task}
        
1. Step 1
1. Step 2
```
the generated DITA `step` elements do not contain `cmd` inside them.

**Comment by jelovirt** [comment]
This is a regression bug caused by supporting tight lists.

**Comment by raducoravu** [comment]
Thanks @jelovirt 👍
