### ISSUE TITLE
Remove old project

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#190]
Maybe this older project could be removed completely:
https://github.com/jelovirt/dita-ot-markdown
Whenever I search on Google for this project I find the other one first.

**Comment by jelovirt** [comment]
Changed the old project to private.

**Comment by raducoravu** [comment]
Thanks @jelovirt 
Google still proposes this project but now with a broken link, probably all will be fine after its bots re-index the link.
<img width="838" alt="Screenshot 2023-11-05 at 08 40 06" src="https://github.com/jelovirt/org.lwdita/assets/1005979/52513f8f-2807-478c-adbe-cc0ad15c2313">
