### ISSUE TITLE
DITA tables: How do I prevent duplicating topics when the only difference is a table column? 

### ISSUE THREAD

**Issue by Smibee1392** [jelovirt/org.lwdita#20]
I have to display two tables in two separate documents which essentially contain the same information, but in one of the documents, I have two extra columns. For example: 

In Manual A, the table needs to look like: 
Name | ID | Description

In Manual B, the table needs to look like: 
Name | ID | Description | Code

Is there any clever way of applying the "principles of conkeyrefing" a column in? I know tables are built on a row-basis, but, is there any way I could prevent simply duplicating my content because of a single column?

**Comment by jelovirt** [comment]
This is something that cannot be marked up with MDITA.

In DITA or XDITA you could have just one table with all columns and on the other topic you could filter out the column you don’t need.
