### ISSUE TITLE
Improper conversion of "audience" metadata

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#203]
If in the Markdown file I have:

    ---
    audience: Audience
    ---

the generated DITA XML content contains:

     <audience audience="Audience"/>

So the "Audience" value goes as the value of the profiling attribute "audience", I think maybe it should go as the value of the attribute @type

https://www.oxygenxml.com/dita/1.3/specs/langRef/base/audience.html

**Comment by kirkilj** [comment]
Is it safe to assume that this doesn’t affect the handling of {.audience=novice} in an attribute list? These get converted to the audience filtering attribute still, correct?

**Comment by raducoravu** [comment]
Thanks @jelovirt 👍
