### ISSUE TITLE
markdown2dita: notes in lists

### ISSUE THREAD

**Issue by amyhiggins** [jelovirt/org.lwdita#204]
If I try to add a note to a list item (ordered or unordered list), I receive the following error when building with any output format I try:
> Error: Failed to run pipeline: class com.vladsch.flexmark.ext.admonition.AdmonitionBlock cannot be cast to class com.vladsch.flexmark.ast.ListItem (com.vladsch.flexmark.ext.admonition.AdmonitionBlock and com.vladsch.flexmark.ast.ListItem are in unnamed module of loader java.net.URLClassLoader @eed1f14)

This is the code I've tried:
```
1. First item
2. Second item

    !!! note
        Note about the second item.

3. Third item
```

I can add the note to the bottom of the list for now, but it would be nice if the note could directly follow the list item it's referring to.

**Comment by jelovirt** [comment]
This has already been fixed in [5.6](https://github.com/jelovirt/org.lwdita/releases/tag/5.6.0). See https://www.dita-ot.org/plugins/org.lwdita/5.6.0 how to install the latest version of LwDITA plug-in to DITA-OT.
