### ISSUE TITLE
Render in published output strikethrough content

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#21]
A strikethrough in the Markdown content:

          ~~abc~~

is converted in the DITA content to a "ph" with status "deleted".
How about if the plugin could also contribute plugin extensions for HTML and PDF based outputs to convert ph with status="deleted" to content which actually appears strike-through in the published output?

**Comment by jelovirt** [comment]
This is out of scope for LwDITA plugin and should be instead be implemented natively by PDF or HTML5 plugins or by a custom styling plugin.

**Comment by jelovirt** [comment]
Since it’s not univerally correct formatting for delete text, my preference is to allow people to handle this the way they want. Also, I prefer to keep this plugin as small as possible.
