### ISSUE TITLE
Footnotes in Markdown

### ISSUE THREAD

**Issue by martab0** [jelovirt/org.lwdita#211]
What is the recommended way of writing footnotes in Markdown for lwdita processing (if any)? The GitHub standard `[^1]` Footnote does not seem to work consistently.
```markdown
[^1]: Footnote content 
```

**Comment by michael-nok** [comment]
[Related issue](https://github.com/jelovirt/org.lwdita/pull/208)

**Comment by jelovirt** [comment]
@martab0 Could you show your content that doesn't work? Preferably a full example that you can run with DITA-OT from start to finish, but with as few files and content as possible to display the issue. Attach or paste it here.

**Comment by jelovirt** [comment]
For example [footnote.md](https://raw.githubusercontent.com/jelovirt/org.lwdita/master/src/test/resources/markdown/footnote.md) is the test case for footnotes.

**Comment by martab0** [comment]
@jelovirt, thank you! I pulled the latest lwdita and I checked that footnotes [^1] work in Markdown. There are some inconsistencies how our custom plug-ins handle them, but that appears to be our custom plugin issue, not lwdita issue.
