### ISSUE TITLE
Preserve line breaks in table cells

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#216]
If a Markdown table cell has a "br" element inside it it would be great if it could be converted to the "linebreak" processing instruction so that it can make it through to the other side and produce a line break in the HTML or PDF output.

```
# abc

| **1** | **2** |
| ------------ | ---------------- |
| test         | line1<br />line2 |
```

**Comment by michael-nok** [comment]
Use <p> tags instead to create separate lines.

```
| **1** | **2** |
| ------------ | ---------------- |
| test         | line1<p>line2 </p>|
```

**Comment by jelovirt** [comment]
Closing as this is a confirmed workaround
