### ISSUE TITLE
If I add a line break after I end the last line of text with two spaces I should get a new paragraph

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#26]
Moving this issue:
https://github.com/jelovirt/dita-ot-markdown/issues/60
to the new plugin.

This small Markdown content should be interpreted as two paragraphs because the first line of text ends with two spaces.

    some words  
    other words

See:

https://daringfireball.net/projects/markdown/syntax#p

    When you do want to insert a
    break tag using Markdown, you end a line with two or more spaces, then type return.

Of course with DITA there is no "br" but we should probably create a new paragraph for it.

**Comment by jelovirt** [comment]
A hardline break is already converted into a `<?linebreak?>` processing instruction, see https://github.com/jelovirt/org.lwdita/wiki/Syntax-reference#hard-line-breaks

If two paragraphs are needed, users can add a custom preprocessing step to split the `<p>` element by the processing instruction. By not doing this for all cases allows retaining the info about hard line break and enables Markdown to DITA to Markdown round-tripping.

**Comment by raducoravu** [comment]
@jelovirt Ok, agreed.
