### ISSUE TITLE
no line break between <cmd> and <stepresult> in markdown output

### ISSUE THREAD

**Issue by thendarion** [jelovirt/org.lwdita#27]
DITA input

```xml
<step>
  <cmd>step</cmd>
  <stepresult>result</stepresult>
</step>
```

is rendered as

```markdown
1. step result
```

without any indication of the two being separate things.

**Comment by thendarion** [comment]
oops, forgot to command block the XML part last time. corrected :)

**Comment by jelovirt** [comment]
There is no spec that mandates how DITA Task step should be output in Markdown. Thus the current output can be considered correct. However, it might make sense to output the step command on a separate line, followed by the rest of the step contents.
