### ISSUE TITLE
XSLT Error: Unsupported AST nodes link/cite

### ISSUE THREAD

**Issue by infotexture** [jelovirt/org.lwdita#28]
Generating GitBook output for the DITA-OT docs throws XSLT errors:

```bash
[xslt] ERROR: Unsupported AST node link
[xslt] ERROR: Unsupported AST node cite
```

## Steps to reproduce

In the `docsrc/` directory, run `dita --input=userguide.ditamap --format=markdown_gitbook`.

**Comment by ritti** [comment]
This issue is similar to [XSLT Error: Unsupported AST node subscript/superscrip](https://github.com/jelovirt/org.lwdita/issues/18) that is unfortunately not fixed (see new comment)

**Comment by robander** [comment]
Also had one of our customers run into this today, but with an additional XSLT `key()` failure at the end that's likely unrelated.

**Comment by infotexture** [comment]
👍 Verified that DITA-OT docs output is generated without errors with 2.0.7.
