### ISSUE TITLE
MDITA fails on footnotes

### ISSUE THREAD

**Issue by infotexture** [jelovirt/org.lwdita#30]
While testing the XDITA plug-in per https://github.com/dita-ot/dita-ot/pull/3108#issuecomment-430815475, building output from [org.oasis-open.xdita/samples/remotelighting.ditamap](https://github.com/oasis-tcs/dita-lwdita/blob/v0.2.1/org.oasis-open.xdita/samples/remotelighting.ditamap) failed with an error related to the use of footnotes on [Line22 of remote-components.md](https://github.com/oasis-tcs/dita-lwdita/blame/v0.2.1/org.oasis-open.xdita/samples/mdita/remote-components.md#L22):

    Error: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.footnotes.Footnote

**Comment by jelovirt** [comment]
Fixed in #31

**Comment by infotexture** [comment]
The changes in #31 resolve the footnote error and allow processing to continue, but the specific combination of table and footnote markup in [the XDITA sample file](https://github.com/oasis-tcs/dita-lwdita/blob/master/org.oasis-open.xdita/samples/mdita/remote-components.md) is not rendered correctly _(table output is broken)_.

To reproduce, run:

```console
dita --input=src/main/plugins/org.oasis-open.xdita.v0_2_1/samples/remotelighting.ditamap --format=html5 --output=out/xdita
```

and navigate to `out/xdita/mdita/remote-components.html`.

The table in the Markdown source file is [rendered correctly on GitHub](https://github.com/oasis-tcs/dita-lwdita/blob/master/org.oasis-open.xdita/samples/mdita/remote-components.md), so the error appears to be somewhere in the LwDITA parser.

**Comment by infotexture** [comment]
Table rendering issues resolved with changes to sample files in https://github.com/oasis-tcs/dita-lwdita/pull/24.

Oddly enough the superscripted footnote marker is missing in the final table cell, but that was the case before my changes too, so there seems to be a complication in the interaction between table and footnote markup.
