### ISSUE TITLE
Conrefs work when generating DITA but not PDF, keys not at all

### ISSUE THREAD

**Issue by larrykollar** [jelovirt/org.lwdita#32]
Environment: MacOS Mojave, DITA-OT 3.1, and lwdita.org 2.0.6.

I've attached a minimal example of a map, a content topic, and a collection-of-snips topic. The latter contains a conref paragraph and a shortcut reference link.

When converting to DITA with `dita --input=reusetest.ditamap --format=dita`, the conref'ed paragraph appears in the output, but not the shortcut.

When publishing to PDF with `dita --input=reusetest.ditamap --format=pdf`, neither the conref'ed paragraph nor the shortcut appear in the PDF.

[con_test.zip](https://github.com/jelovirt/org.lwdita/files/2527730/con_test.zip)

**Comment by carlosevia** [comment]
Larry: Your key has to be declared in the map

**Comment by jelovirt** [comment]
What Carlos said.
