### ISSUE TITLE
No renderer configured for com.vladsch.flexmark.ext.aside.AsideBlock

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#38]
Tested with DITA OT 3.2.1
If I have an invalid Markdown table (the last line of the table does not end in pipe):

        # Title
        
        abc
        
        | P1 | P1 | P3 | P4 |
        | --- | --- | --- | --- |
        |  | R1 | R2

the Markdown to DITA plugin breaks the DITA to HTML output with:

           DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:62: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.aside.AsideBlock

Ideally either the errors would not be that criptic or there would be some better fallbacks or maybe even some line numbering information would be displayed in the error to instruct the end user as to where the problem is because the Markdown file could be quite large.

**Comment by jelovirt** [comment]
Disabled Aside extension in ef1522dc589f9c7ff3c27dd845f41b5513674f34
