### ISSUE TITLE
YAML header causes error message: Error: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.jekyll.tag.JekyllTagBlock 

### ISSUE THREAD

**Issue by mtooke** [jelovirt/org.lwdita#39]
When I set my dita map topicref format attributes to _markdown_, I get the following error:
 
> Error: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.jekyll.tag.JekyllTagBlock

After our email conversation, it was determined that this was caused by the YAML header in the files. When I removed the YAML headers, the files built fine.

This error occurred using DITA-OT 3.2.

**Comment by jelovirt** [comment]
@mtooke could you add an example of a file that causes this error here?

**Comment by mtooke** [comment]
[editing-menus.txt](https://github.com/jelovirt/org.lwdita/files/2737364/editing-menus.txt)

**Comment by mtooke** [comment]
[main2.zip](https://github.com/jelovirt/org.lwdita/files/2737369/main2.zip)

I've included my entire set of files to give you better context for what I'm experiencing. Hopefully this is OK.  I've been commenting out my map in order to isolate other bugs. If you take a look in the file how-do-i-duplicate-my-store.md, line 55 is causing the error:

Error: Failed to run pipeline: Failed to merge map C:\ditaout\shopify_temp\C:\d3\shopify\main2.ditamap: C:\ditaout\shopify_temp\C:\d3\shopify\main2.ditamap (The filename, directory name, or volume label syntax is incorrect)

It seems to be related to both links in that sentence:

Orders can **not** be imported into a store through the Shopify admin, but they **can** be imported through the [Shopify API](/api). **This is not supported by Shopify**. We recommend visiting [our Shopify Experts marketplace](/experts.shopify.com) to find a developer for hire if you must import orders into the new store.

I get this same error on multiple files in this map.
