### ISSUE TITLE
Support for conversions to LightWeight DITA Map

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#45]
In the specs there seems to be an example of an "MDITA Map":

http://docs.oasis-open.org/dita/LwDITA/v1.0/cnprd01/LwDITA-v1.0-cnprd01.html#example-of-an-mdita-map

Maybe if in the main DITA Map you have a topicref like this:

     <topicref href="map.md" format="mditamap"/>

you could have an extra parser to convert that to a LightWeight DITA Map.

https://github.com/oasis-tcs/dita/pull/308

**Comment by jelovirt** [comment]
@robander are you able to comment, does the LwDITA TC have a magic format name in mind for MDITA maps?

**Comment by robander** [comment]
I checked with Carlos, and he's going to run this question by the LwDITA subcommittee, but `mditamap` seems likely to me.

**Comment by carlosevia** [comment]
I think mditamap is simple enough. I will report back once we get some feedback from the subcommittee.

**Comment by ahouser** [comment]
How do we handle LwDITA-specific items like this in the specs and grammar files? For a stand-alone LwDITA implementation, this is easy (LwDITA spec; LwDITA grammar files). But a DITA processor that also supports LwDITA must recognize these @format attribute values, that are not listed in the DITA spec and are not legal per the DITA grammar files.

**Comment by jelovirt** [comment]
@carlosevia any activity on this?

**Comment by carlosevia** [comment]
It has a pending action item with the DITA TC... @ahouser is working on it

**Comment by jelovirt** [comment]
@carlosevia @ahouser is there a public issue tracker I can link to?

**Comment by jelovirt** [comment]
[Markdown DITA map input](https://github.com/jelovirt/org.lwdita/wiki/Markdown-Syntax-reference#markdown-dita-map-syntax) has been implemented, but LwDITA spec still draft doesn't specify a file name extension for MDITA maps.

**Comment by jelovirt** [comment]
It seems the file name extension for LwDITA are in DITA 2.0 spec pages for [`@format`](https://dita-lang.org/dita/archSpec/base/theformatattribute.html) attribute 🤔. I assume this will be moved to LwDITA spec at some point, but will take this as something that can be implemented for the draft.
