### ISSUE TITLE
Problem with formats supported by LWDita plugin

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#47]
The plugin.xml declares the following format parsers:

       <parser format="html" class="com.elovirta.dita.html.HtmlReader"/>
      <parser format="hdita" class="com.elovirta.dita.html.HtmlReader"/>

Two possible problems:
1) Shouldn't the "hdita" format use the "HDitaReader" instead of "HtmlReader"?
2) I do not quite agree that the "html" DITA format should be automatically handled by this plugin.
For example if in my topic I have a reference to some HTML document from my project:

        <p><xref format="html" href="test.html"/></p>

why should it be parsed as a DITA topic? Maybe I want to keep this HTML document separate from my PDF and I just want to refer to it. And now I have no control over this behavior, I need to comment out parts of the plugin and run the integrator to remove this automatic handling of the "html" format.
How about if we just add the processor on some specific format like "htmlDita" which would mark that we want the HTML to be interpreted as DITA?

**Comment by robander** [comment]
I've turned off parsing for `format="html"` in our instance of DITA-OT; it's a common way to refer to local HTML files that already exist and should not be converted.

**Comment by raducoravu** [comment]
@robander so did I in the DITA OT bundled with Oxygen.

**Comment by infotexture** [comment]
Per https://github.com/dita-ot/docs/issues/262#issuecomment-510046822:

> The conversion from HTML to DITA should _not_ be automatic. 
> 
> To parse an HTML file as HDITA, the `@format` attribute should be set to `hdita` as described in the docs:

```xml
<topicref href="hdita-topic.html" format="hdita"/>
```

> If topicrefs with `format=html` are currently being converted to DITA, that sounds like a bug in the LwDITA plug-in  […] .
