### ISSUE TITLE
Unable to append HTML content - Java API

### ISSUE THREAD

**Issue by cinthyargc** [jelovirt/org.lwdita#55]
### Description
While using DITA-OT Java API, I am unable to append HTML content into my PDF, getting below error:

```
6365 [INFO ] Processing file:/.../ditamapfile/report.html to 
file:/.../javatmp/1562711388902/c6efa7d04b7ef9aa6f47d9f67a8b226ae4362426.html
6366 [ERROR] [DOTJ013E][ERROR] Failed to parse the referenced file 
'file:/.../ditamapfile/report.html'.: com.elovirta.dita.html.HtmlReader
```

However, if I call `dita` on the command line this error is not thrown, and the HTML is appended.

I have tried with below ditamap:
```xml
...
    <appendix navtitle="Report">
      <topicref format="hdita" href="content.html" locktitle="yes" 
navtitle="Report" scope="local"/>
    </appendix>
    <backmatter>
....
```

And below JAVA Code:
```java
Processor ditaProcessor = ditaProcessFactory.newProcessor("pdf")
			.setInput(new File("/.../ditamapfile/ip_ii_new.ditamap"))
			.setOutputDir(new File(outputDir))
			.setProperty("args.input", "/.../ditamapfile/ip_ii_new.ditamap")
			.setProperty("org.dita.pdf2.i18n.enabled", "false")
			//.setProperty("args.filter", filterList.toString())
			.createDebugLog(true);

ditaProcessor.run();
```

I have tried with format equal to html and hdita, and both are giving the same error.

**Environment:**
MacOs
DITA-OT 3.3.2

Thank you!

**Comment by cinthyargc** [comment]
I have updated to latest version 2.2.2, but I am still unable to append content getting same error:

```
4312 [ERROR] [DOTJ013E][ERROR] Failed to parse the referenced file 
'file:/.../1AUT1J7.csp.html'.: com.elovirta.dita.html.HtmlReader
```

**Comment by cinthyargc** [comment]
The issue was not with the parser itself, it was my classpath, I was missing below required jars:

![image](https://user-images.githubusercontent.com/37708042/61062193-5ade9e80-a3c3-11e9-9c5f-7050067d45a7.png)

It will be great if the log could give this kind of information, perhaps a message like: "Missing required dependencies, review Plug-in repository", or something like that, it would be very useful 😃

**Comment by raducoravu** [comment]
You probably need to include in the Java classpath all the libraries from the "plugins\org.lwdita\lib" folder.
You should basically look inside the file "config/env.bat" and besides adding all the JAR libraries from the "DITA-OT\lib" folder also add all the JARs specified in the "env.bat"
