### ISSUE TITLE
Flexmark license is BSD, not Apache 2.0

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#56]
Feedback from our legal:
1) The file org.lwdita/blob/master/licenses/flexmark-license.txt should include the contents from https://github.com/vsch/flexmark-java/blob/master/LICENSE.txt (because right now it has an Apache 2.0 license included).
2) The file "https://github.com/jelovirt/org.lwdita/blob/master/NOTICES" should specify BSD 2.0 for flexmark instead of Apache 2.0.

**Comment by jelovirt** [comment]
Fixed by 0339cb6cb80e7a92023db88210ad1b7d84e44875

**Comment by raducoravu** [comment]
@jelovirt the "https://github.com/jelovirt/org.lwdita/blob/master/NOTICES" file also specifies the flexmark license as Apache 2.0.
