### ISSUE TITLE
No possibility to create the equivalent of a DITA table with a title

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#6]
For images you can specify a title and the corresponding DITA topic will have a figure:

https://github.com/jelovirt/dita-ot-markdown/wiki/Syntax-reference#images

Ideally we would have some similar way of doing this to specify a title for the Markdown table and have that converted to a DITA table containing a title.

**Comment by thendarion** [comment]
this is true the other way around too.
if my DITA table has a title, it's omitted from the markdown output 😢

**Comment by raducoravu** [comment]
Well at least it's consistent :smirk:

**Comment by jelovirt** [comment]
Table captions have been supported for a while now, closing as obsolete.
