### ISSUE TITLE
"_" is escaped in Markdown output with "\_"

### ISSUE THREAD

**Issue by ritti** [jelovirt/org.lwdita#61]
Occurs in DITA-OT 3.4 where a DITA XML file is transformed to markdown_github.

Attached is the source dita-xml file and the resulting markdown file when transformed via command

`dita-ot-3.4\bin\dita" --input=Test.ditamap --output=out\markdown --format=markdown_github`

![2019-11-21 06_44_13-Window](https://user-images.githubusercontent.com/14054526/69307318-7c318000-0c2a-11ea-88e4-6ccfe287274c.png)

**Comment by jelovirt** [comment]
Fix: don't escape `_` in code phrase.

**Comment by jelovirt** [comment]
This seems to have been changed at some point and `_` is no longer escaped in code spans.
