### ISSUE TITLE
MD link with ? in the URI fails the build

### ISSUE THREAD

**Issue by robander** [jelovirt/org.lwdita#64]
I have this link in an MD file:
`Link to ["something"](second.html?pos=3)`

The `?pos=3` part results in this build failure:
```
debug-filter:
   [filter] Processing file:/C:/dcs/test/jira530/second.md to file:/C:/dcs/test/jira530/temp/second.md
Error: java.lang.IllegalArgumentException: URI has a query component
```

I'm not sure if this is really an issue in `debug-filter` parsing the URI, or if something in the `lwdita` plugin is converting it with the wrong set of attributes -- likely both -- opening this to make sure I don't lose track of the issue.

Sample files attached.
[jira530.zip](https://github.com/jelovirt/org.lwdita/files/3979039/jira530.zip)

**Comment by jelovirt** [comment]
Fixed already
