### ISSUE TITLE
Misleading error message when Markdown DITA files are not UTF-8 encoded

### ISSUE THREAD

**Issue by ritti** [jelovirt/org.lwdita#67]
Occurs in DITA-OT 3.4 where a Markdown DITA file is transformed to markdown_github.

The Markdown DITA file is UTF-8-BOM encoded (attached file) and included in a Test.ditamap:

`<topicref href="Intro.md" navtitle="Intro" format="markdown" />`

When the following DITA command is executed:
`dita-ot-3.4\bin\dita" --input=Test.ditamap --output=out\markdown --format=markdown_github`

the following error appears in the log file:

` [gen-list] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:/C:/_WS_local/TestFormat/Intro.md'.: Failed to parse Markdown: Header level raised from 0 to 2 without intermediate header level
`
The header levels in the Markdown DITA file are correct.

[MDFiles.zip](https://github.com/jelovirt/org.lwdita/files/4296612/MDFiles.zip)

This error message is completely misleading. No one who is writing markdown content expects with this error message that the content is not correctly encoded.

**Comment by raducoravu** [comment]
It's strange because there is code written:

com.elovirta.dita.markdown.MarkdownReader.consumeBOM(InputStream)

which would consume the BOM from the input stream before processing it further.

**Comment by raducoravu** [comment]
@jelovirt I opened a pull request for this.
Possibly also in the "AbstractReaderTest" you could have created the SaxSources directly over URL locations instead of also opening and providing the input streams, in order to be closer to what happens when the code is used from the DITA OT.
