### ISSUE TITLE
Treat links to fragments(headers) in the same markdown file as internal cross references   

### ISSUE THREAD

**Issue by drewzhao** [jelovirt/org.lwdita#69]
## Bug report

I use the the org.lwdita plugin bundled with DITA-OT 3.4.1 to transform markdown files to pdf.
 
The markdown links to headers in the same file do not work in the pdf output. 

Example input file `abc.md` as below:

```
# title of abc

1. See [xyz](#xyz)

2. See [xyz](abc.md#xyz)

## xyz

Lorem Ipsum .
```

## Expected behavior

In the example above, I expect `Link 1` to work.  

## Actual behavior

`Link 1` does not work. 

So I made an experiment to create Link2, where I prefixed the header id from `Link1` with the file name and `Link 2` worked. But why? I thought because `Link 1` is linking to a header within the same file instead of an external md file, so I shouldn't have to provide the file name in the xref.

Here is an output using the default transtype `pdf`:

![image](https://user-images.githubusercontent.com/52232940/78966092-797bec80-7b31-11ea-8ec5-fc5b3d8d85da.png)

## `Link 1` works fine with DITA-OT 3.3.2

I switched back to DITA-OT 3.3.2 and `Link 1` worked. So I compared the xsl-fo outputs for `abc.md` by DITA-3.3.2 and DITA-OT 3.4.1, and found that `Link 1` was transformed differently by the two DITA-OT versions.

**Fo from DITA-OT 3.4.1**

`Link 1` is transformed to:

`See <fo:basic-link color="blue" external-destination="url('18f945638106eb565a8c6c4cff4558cc3c84f445.md#xyz')">xyz</fo:basic-link>` 

`Link 2` is transformed to:

`See <fo:basic-link color="blue" internal-destination="unique_8">xyz</fo:basic-link><fo:inline> on page <fo:inline><fo:page-number-citation ref-id="unique_8"/></fo:inline></fo:inline>`

**Fo from DITA-OT 3.3.2**

`Link 1` and `Link 2` are both transformed to:

`See <fo:basic-link color="blue" internal-destination="unique_9">xyz</fo:basic-link><fo:inline> on page <fo:inline><fo:page-number-citation ref-id="unique_9"/></fo:inline></fo:inline>`

## What I found

The link format `[xyz](#xyz)` in markdown is treated as an external reference (`external-destination`) instead of an internal destination when transformed to xsl-fo, which then causes the link to be invalid in pdf.

**Comment by kirkilj** [comment]
It would help us if this could be fixed.

**Comment by raducoravu** [comment]
@jelovirt maybe you should close this issue as well.

**Comment by drewzhao** [comment]
Fixed by https://github.com/jelovirt/org.lwdita/pull/103
