### ISSUE TITLE
Add some possibility to create DITA superscript (sup) and subscript (sub) elements 

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#7]
Maybe using "^" and "~" to surround those pieces of text.
Something like:

          32^nd^ H~2~O

**Comment by raducoravu** [comment]
Right now for this markdown content:

            # Header 1
            
            1. ^p^p

I get in the DITA content:

      No renderer configured for com.vladsch.flexmark.superscript.Superscript

**Comment by jgranduel** [comment]
Same issue today.
(The markdown was created by a transformation from a .docx document with pandoc which supports this notation.)

**Comment by jhanna-pasco** [comment]
👍 Another vote for this enhancement.

**Comment by raducoravu** [comment]
As a workaround you can use HTML style tags for sup and sub, they seemed to work from what I tested. Entity references seem to work also: https://www.oxygenxml.com/forum/post57825.html#p57825
