### ISSUE TITLE
Plug-in release name format

### ISSUE THREAD

**Issue by infotexture** [jelovirt/org.lwdita#71]
Currently, the list of plug-in releases at https://github.com/jelovirt/org.lwdita/releases names each release in the following format:

> LwDITA for DITA-OT 2.3.2

This is a bit confusing, as it could be read as “this is the version of the LwDITA plug-in that is compatible with DITA-OT version 2.3.2”.

_(The release date of that plug-in version suggests it is designed for use with DITA-OT 3.4.)_

To avoid confusion, it might be better to remove “for DITA-OT” from each release name, and mention the target DITA-OT version in the release info below:

> **LwDITA 2.3.2**
> - [Compatible with | Requires | Supports] DITA-OT 3.4
> - _other release details_
> - ⋮

**Comment by jelovirt** [comment]
Renamed the releases.
