### ISSUE TITLE
Improve error message "Header level raised from 1 to 3 without intermediate header level"

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#72]
Maybe instead of "Header" we should use "Heading".  Ideally the error could maybe report a line and column number in the Markdown file where the heading was encountered.
Also the error message in general does not quite help. I mean, for Markdown to HTML there is no problem to jump from h1 to h4, but somehow for MD to DITA the error message should explain better why this is a problem.
In our case we had a client with the Markdown file opened in Oxygen, with an H4 following an H1 heading, the DITA preview on the right showing this error. The client had no idea what the problem was or how to fix it.

**Comment by ritti** [comment]
Be aware that the same error message appears when the file is not UTF-8 encoded (see #67)
