### ISSUE TITLE
Markdown to DITA Customization

### ISSUE THREAD

**Issue by kirkilj** [jelovirt/org.lwdita#77]
Our R&D groups use CommonMark with a few Python extensions. Their highest priority is to convert an annotation item to DITA <note> elements of a particular type. Is there any possibility of configuring some mapping rules via regex or some other means to handle such extensions during the conversions from Markdown to MDITA or DITA? We would need this to work in OT and in Oxygen during the transparent conversion?

If there are no plans to do so, could we "just" take the lwdita source here and create our own flavor of this conversion to support certain Markdown extensions?

Is anyone else facing this kind of need to bridge the gap between Tech Comm and R&D groups?

**Comment by kirkilj** [comment]
Just checking back since there was no reply on this. @jelovirt

**Comment by jelovirt** [comment]
Configuring how mapping is done is not really supported. Could you add additional information exactly what sort of mapping is needed?

**Comment by kirkilj** [comment]
I was speaking in general terms when I initially wrote this, asking if there was a way, outside of implementing specific java extensions to lw-dita to let organizations to more easily specify a Markdown to AST grammar parser with a set of mapping rules - "when you see pattern x in the Markdown source, convert it to the corresponding DITA elements expressed in a mapping grammar of some sort. This would be used to help account for ALL the crazy variations of Markdown without having to include specific support for each in Lw-DITA itself.

Now that I know about Invisible XML, using its Java implementation in Lw-DITA might allow for this if you were to include iXML support somehow. https://invisiblexml.org/ 

We can discuss at DITA-OT Day. It's just a wild-ass idea at this point.

**Comment by jelovirt** [comment]
@kirkilj coming back to this. Again, can you list actual use cases that you need. What Markdown comes in, what equivalent DITA should come out.

**Comment by jelovirt** [comment]
Closing as support.
