### ISSUE TITLE
The latest release doesn't contain the "org.lwdita-2.4.1.zip" file.

### ISSUE THREAD

**Issue by DunaMariusCosmin** [jelovirt/org.lwdita#78]
I'm trying to download the zip file of the latest release, but I find only the sources in this section: https://github.com/jelovirt/org.lwdita/releases/tag/2.4.1
I think that "org.lwdita-2.4.1.zip" file was missed because the older releases have a file like this.

Thanks,
Cosmin

**Comment by jelovirt** [comment]
Uploaded the dist file
