### ISSUE TITLE
"Pandoc pandoc_title_block extension can be used to group multiple level 1 headers under a common title" Stopped working

### ISSUE THREAD

**Issue by Universum220** [jelovirt/org.lwdita#80]
The feature described in https://www.dita-ot.org/dev/topics/markdown-dita-syntax-reference.html#markdown-dita-syntax-reference__titles-and-document-structure "Pandoc pandoc_title_block extension can be used to group multiple level 1 headers under a common title: "

In 2.3.2 it works
Doesn't work in 3.6

![image](https://user-images.githubusercontent.com/13177760/116543508-6340fa00-a907-11eb-8140-1544a19bbcdf.png)

**Comment by jelovirt** [comment]
The Pandoc extension `pandoc_title_block` was incorrectly implemented and has been removed.
