### ISSUE TITLE
MDITA and @outputclass

### ISSUE THREAD

**Issue by kirkilj** [jelovirt/org.lwdita#81]
Is there any way for a MDITA author to add some annotation that gets translated into an @outputclass? Our biggest use case is for tables. We'd like to be able for the MDITA author to specify a "style" of table to render with options such as table_all_borders, table_no_borders, col_ratios, etc. Our OT plugins would apply a corresponding FO attribute-set or CSS style.

**Comment by jelovirt** [comment]
AFAIK MDITA doesn't support this. While support for Markdown can contain a combination of various Markdown dialects (MMD, GFM), MDITA cannot be extended.

I suggest you use HTML5 tables in MDITA. HTML5 in MDITA may not yet include support for all attributes that can be round-tripped, like `@border`.
