### ISSUE TITLE
Cell spanning not working

### ISSUE THREAD

**Issue by kirkilj** [jelovirt/org.lwdita#84]
See DITA-OT issue https://github.com/dita-ot/dita-ot/issues/3222

**Comment by kirkilj** [comment]
@raducoravu, given what you said about the Java change that would be needed to enable cell spans on dita-ot/dita-ot#3222, the only options to fix this in the near term would be for us to fork this repo or for Jarno to make this fix if he has time. Can others make pull requests on this repo? I see that there are 2 pull requests pending at this moment.

**Comment by raducoravu** [comment]
@kirkilj pull requests can be made, or you can build a copy of the plugin from your fork. In your case do you use tables in HTML format in markdown or in that ASCII form?

**Comment by kirkilj** [comment]
R&D uses ASCII mostly

**Comment by raducoravu** [comment]
If the Markdown tables with cell span are in ASCII format, to make this work that would require a small in the Java code, pasting my investigation from the other issue below:
For the second instance of the table present in ASCII graphics layout, colspans are turned off by default in the "com.elovirta.dita.markdown.MarkdownReader" constructor. If you turn them on and disable append missing columns:

    .set(TablesExtension.COLUMN_SPANS, true)
    .set(TablesExtension.APPEND_MISSING_COLUMNS, false)

it works for the example on this issue.

**Comment by njmuck** [comment]
hi! This solution works for pdf and for html using preprocess, but not for html using preprocess2. It shows this error in html5.topic.common.inner:

[xslt] An empty sequence is not allowed as the result of a call to table:find-entry-end-column#1
[xslt] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the result of a call to table:find-entry-end-column#1

**Comment by raducoravu** [comment]
@kirkilj maybe you can add a separate issue for the preprocess2 problem.
