### ISSUE TITLE
Newline syntax = 2 spaces at EOL ignored

### ISSUE THREAD

**Issue by Schelmenzunft** [jelovirt/org.lwdita#86]
Adding 2 spaces at EOL does not produce a new line but is ignored.

This MD feature is really handy to add explanations to (un)ordered lists, f. e.

1. First list item.
1. Another list item.  
With a following line after 2 blanks.

It works inside this editor, see above. Woud be helpful if it would work in lwdita also.

**Comment by raducoravu** [comment]
@Schelmenzunft can you maybe attach a zip containing a sample markdown file? Also maybe a screenshot with how you would like the published HTML content to look and how it looks now?

**Comment by Schelmenzunft** [comment]
@raducoravu I attached a ZIP with the sample MD file and 3 screenshots: Oxy24 Preview with LWDITA (no line breaks), same with preview HTML (line breaks), exported PDF with Chemistry (no line breaks).
[#86MDNewlineNotWorking.zip](https://github.com/jelovirt/org.lwdita/files/7950421/86MDNewlineNotWorking.zip)
.

**Comment by raducoravu** [comment]
Those two consecutive spaces are translated in the HTML output as a &lt;br> element which does not exist in DITA.
The Markdown to DITA conversion seems to convert the list item to this:

       <li><p>Another list item.<?linebreak?>With a following line after 2 blanks.</p></li>

so it leaves this extra "<?linebreak?>" marker there which may be useful for the publishing stage, for example in the publishing stage maybe an XSLT customization plugin can match the processing instruction and convert it to an HTML &lt;br> element, especially as the CSS-based PDF output created by Oxygen is based on HTML5.

**Comment by Schelmenzunft** [comment]
@raducoravu Thx for the clarification. I will now close this issue.
