### ISSUE TITLE
Markdown to DITA adds placement="break" to inline images

### ISSUE THREAD

**Issue by Schelmenzunft** [jelovirt/org.lwdita#87]
Exporting a markdown file referenced in a DITA Map that contains inline images adds  *placement="break"* attribute to the <image> element, and that forces a break in the generated output.

Markdown content:
```md
**Speichern** ![Testbild](_img/Allgemeine/speichern.png): Änderungsvorgang/Beschluss speichern.
```
Generated DITA output:
```xml
<image class="- topic/image "
    href="_img/Allgemeine/speichern.png"
    placement="break"
    xtrf="file://users/fjk/Desktop/Beispiel-Hilfethema.md"
    xtrc="image:1;181:15">
  <alt class="- topic/alt "
      xtrf="file:/Users/fjk/Desktop/Beispiel-Hilfethema.md"
      xtrc="alt:1;181:15">Testbild</alt>
</image>
```
Sample Markdown file and referenced image attached.

[InlineImageBreak.zip](https://github.com/jelovirt/org.lwdita/files/7992777/InlineImageBreak.zip)

I would suggest changing *placement="break"* to *placement="inline"* for inline images.

**Comment by jelovirt** [comment]
Seems to work in 3.3
