### ISSUE TITLE
Add possibility to specif image width or scale

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#9]
Sometimes images included in Markdown content are larger and they need to be scaled. So somehow we would need to specify the equivalent of the DITA @width or @scale attributes in the Markdown content.

**Comment by jelovirt** [comment]
Quick search reveals that e.g. GFM had size attributes at some point, but they were abandoned in favour of HTML element. IMO this is the approach to take: fall back on HTML when plain image reference is not enough.

**Comment by raducoravu** [comment]
You will still not be able to specify @scale using HTML approach. How about using header attributes next to the image to specify various attributes on it?

**Comment by jelovirt** [comment]
You can use percentages in width, which is effectively the same as scale.

**Comment by raducoravu** [comment]
We just had someone request for a @scalefit to be generated on the result DITA image:
https://www.oxygenxml.com/forum/post49216.html#p49216

**Comment by hestonhoffman** [comment]
I think I'm seeing some related issues - but let me know if I'm posting in the wrong place. 

**Background**: I publish from a mixed DITA/markdown ditamap to both HTML and markdown. I'm unable to get image scaling to work in my markdown transforms - the transform seems to strip all HTML/DITA/CSS from the source.   

If I use the following in DITA:
```
<image href="./nebula-docs-hero-2x.png" width="423" alt="Project Nebula banner" id="banner"/>
```
I get the following output when I convert to Github flavored markdown:
```
![Project Nebula banner](nebula-docs-hero-2x.png)
```
If I use the following markdown:
```
## No scaling
<img src="nebula-docs-hero-2x.png" alt="hero">

## 400 width
<img src="nebula-docs-hero-2x.png" alt="hero" width="400">

## 200 width
<img src="nebula-docs-hero-2x.png" alt="hero" width="200">
```
I get the following output in my transform:
```
# Testing image scaling

This is a test to see if I can resize this image.

## No scaling

![hero](nebula-docs-hero-2x.png)

## 400 width

![hero](nebula-docs-hero-2x.png)

## 200 width

![hero](nebula-docs-hero-2x.png)
```
Is there a way to get the HTML/CSS properties to persist when running DITA + markdown through a markdown transform? (I've tried both markdown and GitHub flavored markdown)
