### ISSUE TITLE
Add attribute list support for images in Markdown input

### ISSUE THREAD

**Issue by jlacour31** [jelovirt/org.lwdita#91]
## Description
Currently id and outputclass are only available in headings, this could be extended to elements like list-items or images.
We should be able to keep the same format, something like

```md
![Carrot](../../images/Carrot.jpg){#carrot .juice}
```

## Workaround
At the moment the only solution is to embed HTML inside the md file: 

```html
<img src="../../images/Carrot.jpg" id="carrot" outputclass="juice">
```

**Comment by kirkilj** [comment]
Table classes have been requested by several of our R&D colleagues, who would like to standardize on a set of different table styles.

Codeblock is another to indicate syntax coloring styles
